[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"


[build.environment]
  NEXT_PUBLIC_SUPABASE_URL = "https://bsssphmllvqlczvvrmwg.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJzc3NwaG1sbHZxbGN6dnZybXdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3Mjk1MzEsImV4cCI6MjA2NzMwNTUzMX0.T5MzaiXvu6OjCp-KU44dVHhCW8kQYy6hCjbMxB_9P9g"
  SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJzc3NwaG1sbHZxbGN6dnZybXdnIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MTcyOTUzMSwiZXhwIjoyMDY3MzA1NTMxfQ.NM8jEpPnGcpNFSXwBQkU0ktzo479OauMnU290F0hvjo"